### ISSUE TITLE
How to get Apple maps to work on iOS?

### ISSUE THREAD

**Issue by cloudorbush** [teovillanueva/react-native-web-maps-solito-example#1]
Hi @teovillanueva,

Your example works great on react-native-web. 

However, on iOS and Android I keep getting hit with the following error.

I'm wondering if you have any insight into what could be causing this?

![IMG_0869 2](https://user-images.githubusercontent.com/57633368/182263509-99bfc1bc-5283-4afc-ad97-9e31a4b4dc7f.PNG)
![IMG_0870](https://user-images.githubusercontent.com/57633368/182263517-119ddefe-2237-447c-9df8-49aefc19ac08.PNG)

**Comment by teovillanueva** [comment]
Hello @vbylen, Thanks for asking. I assume it's an issue with `react-native-maps`, Are you trying to run a custom expo dev client? Let me know how you are trying to run the app 😃

**Comment by cloudorbush** [comment]
@teovillanueva yes indeed, I'm running it in a dev client on expo SDK 45. My fear is that you are correct 🥶

**Comment by teovillanueva** [comment]
I've just checked and I thinks is maybe a mismatch in `react-native-maps` version. The version in the lib uses version 0.30.2 but the example is using another version i think. Would you mind trying to align slocally the versions? Thanks

**Comment by teovillanueva** [comment]
The problem actually is that `react-native-maps` is not being able to use some native component. I've stumbled upon this issue many times with expo dev clients,sometimes some native part is not included. Rebuilding may work after playing around with package versions 😃

**Comment by cloudorbush** [comment]
it's working 😊
